### ISSUE TITLE
[MISSÃO 2] - Backlog do Produto

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#10]
- Parte conceitual sobre o que se refere cada item do backlog (sucintamente porque isso já vai estar sendo feito na parte do safe)
- Tabela com o nosso backlog 
- Manter bem separado e organizado conforme 
- Usar referências 
- Contextualizar o que backlog

**Comment by suzaneduarte** [comment]
Não esquecer da priorização, anexando parte textual pra descrever nossas escolhas e os prints no miro

**Comment by PabloGJBS** [comment]
Adicionada a página do Backlog ✌
