### ISSUE TITLE
Anexar todos slides utilizados em sala de aula no Pages 

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#13]
Você pode definir se prefere criar uma página separada pra anexar todos os slides utilizados em sala de aula, ou anexar eles de acordo  com o assunto abordado no slide. Ou seja, anexar o slide de visao de geral do produto já nessa parte e assim sucessivamente

**Comment by PabloGJBS** [comment]
Adicionei os 3 slides utilizados nas primeiras apresentações em formato de apresentação no documento
