### ISSUE TITLE
Atualização do Backlog 

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#18]
O backlog já está atualizado no miro, mas é necessário atualizar ele no Pages também antes do Ponto de Controle 1 (dia 16/11): 
 
- [x] Fazer as mudanças pertinentes; 
- [x] Enviar email (seguir padrão dos outros que eu já enviei) para validar os critérios de aceitação, pois já foi validado com o monitor;
- [x] Avisar no wpp do professor que foi enviado o email com os criterios de aceitação 
- [x] Inserir critérios de aceitação no pages;  
- [x] Inserir texto sobre os critérios de aceitação 
- [x] O Miro do backlog atualizado agora é outro, então, tem que atualizar esse link

**Comment by artur-jack** [comment]
tarefas da issue já foram feitas

**Comment by artur-jack** [comment]
Foi corrigido as formas de declarar os requisitos não funcionais
