### ISSUE TITLE
atualização Planejamento Fases em Visão Geral do Projeto 

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#20]
No último feedback o professor informou que deveríamos fazer algumas modificações nessa parte, principalmente no que tange o RAD, portanto, as iterações. 

Atividades: 
- [x] Inserir texto de introdução para iniciar essa parte tentando levar em considerações a forma como o RAD divide as atividades (contextualizar)
- [x] Adaptar o que está dividido em formato de sprints para o formato de Iterações 
- [x] Retirar coisas que são relativas a disciplina de fato (feedback dado em sala de aula pelo professor)
- [x] Alterar datas (por exemplo: data do fim do projeto conforme comentado pelo professor em sala de aula..)
- [x] Verificar o KANBAM e inserir lá as atividades que você acredita estarem faltando (pode adicionar mais iterações caso seja necessário)
- [x] Fazer as alterações na tabela atual para que ela **de certa forma** siga o padrão do kanbam (artefatos precisam conversar entre si)

OBS1 : Para atualizar essa parte das US é preciso que a #18 esteja pronta, mas e quando você for fazer não tiver o número das issues certinhas ainda aqui no pages, mas tenta só manter o número das US que não alteraram e das novas só colocar uns números pra quantidade total que estiver faltando 

OBS2: Link do KANBAM -> https://miro.com/app/board/uXjVNOv3H60=/

**Comment by CarolCoCe** [comment]
Feito!
