### ISSUE TITLE
[PAGES] - Registrar Planning, Review e Retrospectiva 

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#22]
A partir dos dados disponibilizados no Kanbam é possível completar os campos em cada uma das iterações para Planning, Review e Retrospectiva.  

Para realizar essa atividade, você pode utilizar os templates já inseridos no Miro e inserir post-its pra cada item. Posteriormente, deve-se passar para o pages 

Atividades: 

- [X] Criar uma aba no pages pra inserir essas atividades (não precisa ser pra quinta) 
- [x] Organizar de forma que siga o padrão estabelecido no Miro com o Kanbam (artefatos precisam conversar entre si)
- [x] Inserir os posts its no próprio Miro pra cada uma das iterações (a parte dos itens de cada iteração e a divisão delas eu já fiz, só tem que adicionar os outros campos - sim, se necessário retire da sua mente) 
- [x] Adicionar tabela pra cada iteração

**Comment by PabloGJBS** [comment]
so verificar la pra nois ✌
