### ISSUE TITLE
[PAGES] -  PBB e BDD

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#27]
- [x] Iniciar colocando Miro do PBB e BDD

Atividades PBB (que nós fizemos do nosso mesmo): 
- [x] Introdução com fundamentos e conceitos do PBB
- [x] Inserir PBB 
- [x] Inserir priorização do PBB 
- [x] Inserir critérios de aceitação

Atividades BDD (que fizemos para o PBB dos Insurgentes): 
- [x] Introdução com fundamentos e conceitos do BDD
- [x] Inserir link que o Pedro vai fazer na issue # pra explicar que o BDD foi feito a partir da atividade de veri e val dos insurgentes
- [x] Inserir BDD

**Comment by CarolCoCe** [comment]
tudo bonitinho já hehehe
