### ISSUE TITLE
implementação do mini-caderno de atividades

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#37]
# Mini-caderno 

- [x] implementar o mini-caderno na atividade de pesca (realizar pesca e verificar se faz o check no mini-caderno) 
- [x] verificar se já existe a possibilidade de implementação do caderno em alguma outra área 
- [x] colocar fonte do título do caderno em pixel art 

## Pontos para pensar/estudar: 
-  Vai ter atividades do mini-caderno em literalmente todas as cenas? 
- As atividades do mini-caderno aparecem concomitantemente a sequência de ações do usuário ou já ficam lá pré-estabelecidas pra cada sub-região?

**Comment by CarolCoCe** [comment]
Sobre pontos de estudo:

Vai ter em todas as cenas o mini caderno

Do jeito que eu estou tentando fazer vai ser concomitante as atividades. **** Inclusive, desse jeito que to fazendo, pretendo colocar a limitação de subáreas no minimapa pra só poder acessar o que vc já liberou (mas isso não vai ficar visível no mapa pq eu acho que vai ficar feio do jeito que eu to pensando aqui)

Outra coisa sobre o checklist @suzaneduarte , a atividade de pesca nao vai ser a ultima nao? pelo o que eu fiz e pensei, depois que vc pescou os 3 oguiris, vc nem volta pro mapa, vc recebe a chave. A gnt pode fazer uma tela pro crystal ou um segundo quiz com o baú mas não teria que ter alteração no mini caderno pq nem volta pra aquela tela

**Comment by suzaneduarte** [comment]
> Sobre pontos de estudo:
> 
> Vai ter em todas as cenas o mini caderno
> 
> Do jeito que eu estou tentando fazer vai ser concomitante as atividades. **** Inclusive, desse jeito que to fazendo, pretendo colocar a limitação de subáreas no minimapa pra só poder acessar o que vc já liberou (mas isso não vai ficar visível no mapa pq eu acho que vai ficar feio do jeito que eu to pensando aqui)
> 
> Outra coisa sobre o checklist @suzaneduarte , a atividade de pesca nao vai ser a ultima nao? pelo o que eu fiz e pensei, depois que vc pescou os 3 oguiris, vc nem volta pro mapa, vc recebe a chave. A gnt pode fazer uma tela pro crystal ou um segundo quiz com o baú mas não teria que ter alteração no mini caderno pq nem volta pra aquela tela

@CarolCoCe ANAAAAA, dá uma olhadinha na ideia que eu tive pra fazer isso que você tá falando lá na issue #36 

agora sobre a sequência.. depois que você pega a chave você precisa abrir o baú, então, na minha cabeça aparecia no mini-caderno a atividade de procurar o baú para abri-lo, não? e dai sim essa seria a cena final do crystal aparecendo de dentro do baú

**Comment by CarolCoCe** [comment]
- [x] casa
- [x] casa avo
- [x] pracinha
- [x] sede faccao
- [x] farol

**Comment by CarolCoCe** [comment]
Feito!
