### ISSUE TITLE
sprites da mãe da crys animada 

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#39]
# sprites mãe da crys 

- [x] fazer as artes da mãe dela animada bonitinha representando uma mãe 

obs: coloquei os dois pra vocês poderem conversar e definir quem ta mais tranquilo pra fazer porque isso não é tão urgente assim então façam quando estiverem com a cabeça cheia de desenvolver no godot e tals sabe

**Comment by CarolCoCe** [comment]
@artur-jack o brabo já fezzzzz
