### ISSUE TITLE
comandante estelar 

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#40]
- [x] abrir votação no nosso grupo pro time escolher qual das duas versões da arte do comandante eles preferem 
- [x] fazer a arte da tela de fundo em que o comandante estelar vai aparecer 
- [ ] inserir diálogo com o comandante pela tela (disponibilizado por euzinha na #32 ) na subregião da sede

**Comment by artur-jack** [comment]
Estrutura já está pronta. Falta o texto do diálogo
