### ISSUE TITLE
estabelecer eventos dos três artefatos 

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#47]
- [x] mini mapa visual 
- [x] mini mapa invisível 
- [x] mini-caderno

**Comment by CarolCoCe** [comment]
![image](https://github.com/mdsreq-fga-unb/2023.2-Crystaleum/assets/65306804/4c00fd11-f912-4e39-9fe3-d33b9638e22b)

**Comment by CarolCoCe** [comment]
Amarelo são os eventos e em branco as atividades

**Comment by CarolCoCe** [comment]
Settar eventos

- [x] evento A
- [x] evento B
- [x] evento C
- [x] evento D
- [x] evento E
- [x] evento F

**Comment by CarolCoCe** [comment]
OK!
