### ISSUE TITLE
Planejamento das Fases e/ou Iterações do Projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-Crystaleum#5]
**Produto(entrega)** = aqui, vc apresentam várias atividades e temas da disciplina, como: 

- Definição dos Fundamentos de Eng. Software 
- Definição dos processos, valores e princípios de Engenharia de Requisitos 
- Definição dos Tipos de Requisitos e Regras de Negócio 
- Definição dos Problemas e Necessidades
- Aspectos humanos e sociais da Engenharia de Requisitos 
- Atividades e Técnicas de ER 
- Início das atividades de Estudo do framework Godot

Refaçam a tabela, por favor, registrando os PRODUTOS que serão entregues e não atividades ou temas.

**Comment by suzaneduarte** [comment]
- Acredito que como você já está mais afrente na parte do desenvolvimento da arte, consiga estipular essa parte no cronograma de forma mais específica conforme solicitado pelo professor. 
- Também acredito que a arte irá caminhar de forma muito paralela com o desenvolvimento, então, conforme for estipulando a parte da arte, consequentemente, irá conseguir definir a do desenvolvimento também 
- Formatar tabela 

Se precisar de qualquer ajuda estou à disposição, por isso me coloquei como assignees nessa issue também

**Comment by CarolCoCe** [comment]
Resolvido! A tabela se encontra na Visão Geral do Projeto > Planejamento de fases
