### ISSUE TITLE
Cena de diário do avô

### ISSUE THREAD

**Issue by CarolCoCe** [mdsreq-fga-unb/2023.2-Crystaleum#55]
#Cena do diário do avô 

# Descrição 

Abrir uma cena em forma de livro aberto contando que o avo era de uma facção do comando estelar e entrou nela depois de estudar muito e conversar com pessoas na pracinha da ilha.

# Descrição da cena 

Movida por sua curiosidade, você vai até a antiga casa abandonada do seu avô para tentar encontrar a chave perdida, porém, nessa incessante busca acaba por encontrar outro tesouro: o diário dele, a qual descreve detalhes sobre o comando estelar, importância de ser de facções, localização dos líderes da facções... etc etc 

O diário também esta escrito que ele  descobriu um crystal muito poderoso mas ele estava sendo perseguido pelas grandes corporações por causa dele. 

# Ações

Após falar coma a mãe, Quando clicar no diário do avo (ou interagir)

**Comment by artur-jack** [comment]
Estrutura pronta! Falta inserir o texto do diálogo.
