### ISSUE TITLE
adicionar evento da porta 

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#59]
estou adicionando as animações das portas e seu trabalho será: 

- [x] adicionar interação da crys com a porta, de forma que quando o usuário clicar na porta ela abra (não precisa colocar botão só fazer igual tá no mini mapa); 
- [x] inserir evento em que a animação só irá funcionar se o usuário apertar na porta

**Comment by PabloGJBS** [comment]
a porta so abre se interagir com ela :)
