### ISSUE TITLE
Matriz comunicação

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-Crystaleum#6]
Não entendi, pq colocaram isso na matriz de comunicação.

Outra coisa, backlog de requisitos e mapa de histórias, são excludentes. É um ou outro.

![image](https://github.com/mdsreq-fga-unb/2023.2-Crystaleum/assets/68402547/5e810acb-f2fc-4cdc-8aac-76f8ce8903f6)

**Comment by suzaneduarte** [comment]
- Ajustar tabela para que fique cada tópico em uma linha 
- Realizar ajustes solicitados pelo professor 
- Realizar ajustes solicitados pelo monitor 
- Comparar com matriz de comunicação dos repositórios dos outros semestres 

## Feedback do monitor: 

Duas primeiras linha da matriz: ok! Duas últimas linhas da matriz: Realizar a cada três semanas essas conversas pode não ser a melhor escolha tendo em vista o processo de ER e de SW escolhidos; e a lista de produtos gerados destaca possibilidades de produtos, e não aqueles que sempre serão gerados durante aquela reunião.
