### ISSUE TITLE
[BUGS] - ULTIMO GÁAAAAAAAAAAS 

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#66]
- [x] trocar "opções" por "tutorial" e inserir o tutorial (explicando mini-mapa, caderno e interações com NPCs)
- [x] botão de fechar baú 
- [x] aumentar tamanho do joystick e mais pro meio no mini game de nave
- [x] não dá pra interagir no NPC que tá com o joystick na frente (não sei qual faccao é a dele)
- [x] aumentar tamanho do botão no mini game de nave 
- [x] mudar atividade do mini-caderno (falar com o pirata antes de jogar o game) 
- [x] a porta só abre se tiver entrado em uma facção 
- [x] só dá pra jogar o mini game da nave se tiver falado com o marscicano 
- [x] só da pra jogar o mini game da pesca se tiver falado com o pirata 
- [x] quebrar balões dos diálogos
- [x] mudar caderno só depois de falar com o pirata 
- [x] crys passando de baixo da mesa na casa 
- [x] se você joga o jogo do oniguiri e vence, se for jogar de novo e vencer você não consegue sair 
- [x]  depois de falar uma vez com todos os NPCs não está dando pra falar novamente com alguns deles
- [x] diminuir texto do diário 
- [x] mercenária ta escrito errado em algum dos diálogos 
- [x] diálogo do pós space ta aparecendo no pré 
- [x] pescaria de oniguiris com piratas? - está na forma de resposta pra clicar do diálogo e depois no diálogo também 
- [x] trocar fonte do CRYSTALEUM pra alguma que combine com as fontes dos botões 
- [x] colocar tutorial pra aparecer obrigatoriamente antes da cena da casa da mãe (será? o que acham? discutir no grupo)

**Comment by artur-jack** [comment]
Na do npc que não está dando pra interagir por causa do joystick eu coloquei ele um pouco mais em cima e aumentei a área 2D.
