### ISSUE TITLE
BUGS 2 - APÓS FEEDBACK 

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#67]
- [x] depois de achar o diamante falar pra pessoa explorar o jogo e tals se quiser jogar (mini-caderno)
- [x] revisar erros ortográficos num geral 
- [x] arrumar novamente erro do NPC @taybalau 
- [x] colocar mini-caderno pra falar de novo com o comandante e ser depois do mini game da nave
- [x] só poder sair da sede depois de falar com o comandante 
- [x] encontrar onde ta escrito o nome do universo errado 
- [x] arrumar as perguntas do QUIZ @taybalau 
- [x] quando perder o QUIZ voltar pro começo do QUIZ @artur-jack 
- [x] 5 oniguiri

**Comment by CarolCoCe** [comment]
- [ ] Colocar uma tela pra colocar nossa foto
