### ISSUE TITLE
[MISSÃO 2] - SAFe e User Story

### ISSUE THREAD

**Issue by suzaneduarte** [mdsreq-fga-unb/2023.2-Crystaleum#8]
- Tem que ter uma parte textual pra conceituar/contextualizar cada item do backlog de acordo com o safe 
- Não esquecer de colocar as referências principalmente se for citação 
- Anexar imagens do próprio framework 
- Explicar de que forma o SAFe está aplicado ao nosso projeto (as escolhas que fizemos e afins)

**Comment by CarolCoCe** [comment]
Resolvido!
